### ISSUE TITLE
Close tabs to Left

### ISSUE THREAD

**Issue by SpacePuppeh** [EliverLara/firefox-sweet-theme#59]
I find this very confusing to have my operating system with every other window having a button to close to the left, but yet, Firefox closes on the right. It is slowing down my browsing as I mouse to the wrong sides of each tab when I use this browser.

Would it be possible for you to provide me with a way to change how the close button is presented, moving it to the other side of the tab, on the left?

I have searched around for this for a long time and none of the userChrome solutions worked. This may be due to me using the Sweet firefox theme which overrides my customizations in customChrome.css.

Help would be much appreciated.

Note: The elementaryOS theme does NOT have the tabs on the right. Even though I like this theme better, I might switch just because this is confusing me. I'm also a Mac user.

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, if you still need it, copying this in your `userChrome.css` file  will do the trick:

```css

 .tab-content {
	display: flex;
	justify-content: space-between;
	align-items: center;
	flex-direction: row-reverse;
	margin-top: -1px;
	min-width: 100% !important;
	padding: 0 10px !important;
}

.tab-icon-sound[soundplaying="true"], .tab-icon-sound[muted="true"],
.tab-icon-sound[activemedia-blocked="true"] {
	margin-right: auto !important;
}
.tabbrowser-tab:not([soundplaying]):not([muted]):not([activemedia-blocked]) .tab-close-button {
	margin: 0 !important;
}
.tab-icon-sound {
	margin-left: 6px;
}

.tabbrowser-tab:not([class*="identity-color-"]) .tab-throbber, .tabbrowser-tab:not([class*="identity-color-"]) .tab-throbber-fallback {
	margin-right: 0;
}
.tabbrowser-tab:not([busy]):not([class*="identity-color-"]) .tab-icon-image {
	margin-right: 0;
}

.tabbrowser-tab .tab-label-container {
	margin-left: auto !important;
}
.tabbrowser-tab:not([image]):not([busy]):not([progress]):not([class*="identity-color-"]) .tab-label-container {
	margin-right: auto !important;
}

```
